---
- name: latest epel release
  hosts: localhost
  gather_facts: false

  tasks:
    - name: download latest epel release
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
