---
- name: Install Packages
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install python, gcc and ansible
      yum: 
        pkg="{{ item }}" 
        state=installed
      with_items:
        - python 
        - python-devel
        - python-pip
        - gcc
        - ansible
